version: '3.8'

services:
  # Aplicação principal - Microsserviço de Checkout
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PAYMENT_GATEWAY_URL=http://toxiproxy:8474
      - GATEWAY_PROXY_HOST=toxiproxy
      - GATEWAY_PROXY_PORT=9001
      - REDIS_HOST=toxiproxy
      - REDIS_PORT=9002
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - toxiproxy
      - postgres
      - redis
    networks:
      - entregasja-net

  # Gateway de pagamento simulado (API parceira)
  payment-gateway:
    build:
      context: .
      dockerfile: infra/Dockerfile.gateway
    ports:
      - "4000:4000"
    networks:
      - entregasja-net

  # Toxiproxy - Injeção de falhas na rede
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.9.0
    ports:
      - "8474:8474"   # API de controle do Toxiproxy
      - "9001:9001"   # Proxy para o gateway de pagamento
      - "9002:9002"   # Proxy para o Redis (cache)
    networks:
      - entregasja-net

  # Banco de dados relacional
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: entregasja
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_secret
    ports:
      - "5432:5432"
    networks:
      - entregasja-net

  # Cache (simula o nó de cache que será derrubado no Thundering Herd)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - entregasja-net

networks:
  entregasja-net:
    driver: bridge
